### PR TITLE
Return mutable `Event`

### PR DESCRIPTION
**Pull request by daxpedda**
Forgive me for my naivety, but is it possible to return a mutable `Event` here instead?

### CODE REVIEW

**Comment by onurzdg** [comment]
I would like to understand why you would want to do this. [Event](https://github.com/tokio-rs/mio/blob/master/src/event/event.rs#L21) itself does not offer any mutable methods. The only benefit of making this mutable would be having access to [clear()](https://github.com/tokio-rs/mio/blob/master/src/event/events.rs#L184) method on Events. However, poll already clears the previous events before polling anything.

**Comment by daxpedda** [comment]
I did it for https://github.com/rust-windowing/winit/pull/1875, I don't remember anything honestly and I have no clue why I made this PR anymore, should probably write more next time in the OP. Feel free to close it if it doesn't make sense to you.

**Comment by onurzdg** [comment]
I think you might hava a valid argument here. However, I'd like to not expose `Events` directly as mutable for encapsulation reasons. 
I think I am going to go ahead and add a `clear(&mut self)` method on `Poll` to clear the already polled events.
I am also going to expose another method called `polled_events` to be able to give access to the already retrieved `Events` after calling `wait`. On a side note, I think naming this `wait` was a mistake on my part, which I should fix.

I think, if I do these things, one should not have to explicitly create  an `Events` object to pass around, which was the whole idea behind wrapping Poll.

**Comment by onurzdg** [comment]
Took care of it [here](https://github.com/onurzdg/mio-misc/pull/7).
Published it to crates.
Thanks for bringing this to my attention.

**Pull request closed without merging**
